--CREATE DATABASE CONTROLE_MERCADORIAS

--USE CONTROLE_MERCADORIAS

--CREATE TABLE MERCADORIA_ENTRADA(
--    ID INT PRIMARY KEY IDENTITY (1, 1),
--    MERCAD_NOME VARCHAR (30) NOT NULL,
--    FABRICANTE VARCHAR (30)  NOT NULL,
--	  TIPO VARCHAR (30),
--    DESCRICAO TEXT,
--    DATA DATETIME,
--    QUANTIDADE INT NOT NULL,
--    LOCAL VARCHAR (50)  NOT NULL
--)

--CREATE TABLE MERCADORIA_SAIDA(
--    ID INT PRIMARY KEY IDENTITY (1, 1),
--	  MERCAD_NOME VARCHAR (30) NOT NULL,
--    QUANTIDADE INT NOT NULL,
--    DATA DATETIME NOT NULL, 
--)



